### ISSUE TITLE
Examples require build step

### ISSUE THREAD

**Issue by bradwestfall** [bradwestfall/forms#2]
Currently, one has to run `npm run build:commonjs` before they can run an example like `npm run example:simple`. This is because I couldn't get the examples to import the API code directly from source. 

Right now, here's how examples work. In the `examples` folder there is an `express` server which can be started running one of sever example npm scripts. That server uses a webpack config that is just for examples (different from the main one on root). Currently you'll see in that config that `resolve.alias.src` points to the distribution (build) version of the code. If that changes to point to the `src` folder, then running the example code fails on the JSX of the src. In other words, it's like babel-react isn't being applied to the src folder. There is also a `.babelrc` file in the example folder which is being pulled in. Without that file, running examples fails with JSX on the example code, and with that file it fails on the src code. So I don't really know how to solve this issue.

Obviously, I'd like to have the examples import from src so devs don't have to do the build step in order to run examples. Plus it's causing other problems because when I test code out, I have to build then run the examples, but since the build is transpiled code, the examples show the wrong line numbers for errors

**Comment by gwing33** [comment]
I'd just check to see if it existed with something like `"example:simple": "([[ -d dist/commonjs ]] || npm run build:commonjs) && form=simple npm run example",` (haven't tested this code).

I normally have a `npm run watch:build` command which will build the lib as I change files, I also have it write out the source maps inline in this mode. Then the `npm link` will take care of the rest with correct code mapping.

Then you can have other commands where you... `npm run watch:build & npm run example:simple` if you want to have them go at the same time, and you can decide to put that under maybe something like `dev:example:simple` or something like that.

Probably a better answer but just giving my 2c.

**Comment by bradwestfall** [comment]
The problem with having the built file imported into source is that I lose line-number references. DevTools will tell me what line number from build I'm having a problem at, but not the original file. Unless I can fix that, I'd prefer to have examples load the api from source

**Comment by bradwestfall** [comment]
I solved this by moving webpack configs for examples to the root which allows it to honor babel rules the way I wanted
